version: "3.8"

services:
  api:
    build: .
    container_name: showroom-api
    restart: always
    depends_on:
      - postgres
    networks:
      - showroom-network
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://showroom_user:SuperSecurePass123@postgres:5432/showroom_db
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    container_name: showroom-db
    restart: always
    networks:
      - showroom-network
    environment:
      POSTGRES_USER: showroom_user
      POSTGRES_PASSWORD: SuperSecurePass123
      POSTGRES_DB: showroom_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  showroom-network:
    driver: bridge

volumes:
  pgdata:
