version: "3.8"

services:
  test:
    build: .
    container_name: showroom-test
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: >
      bash -c "pip install -r requirements.txt && 
              pytest --cov=. --cov-report=term-missing"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge