version: "3.8"
services:
  api:
    build: .
    container_name: showroom-api
    restart: always
    depends_on:
      - postgres
    networks:
      - showroom-network
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://showroom_user:password@postgres:5432/showroom_db

  postgres:
    image: postgres:16
    container_name: showroom-db
    restart: always
    networks:
      - showroom-network
    environment:
      POSTGRES_USER: showroom_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: showroom_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: showroom-nginx
    restart: always
    depends_on:
      - api
    networks:
      - showroom-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/easyengine/sites/tl-showroom.equalitech.xyz/config/nginx:/etc/nginx/conf.d

networks:
  showroom-network:
    driver: bridge

volumes:
  pgdata:
