version: "3.8"

services:
  api:
    build: .
    container_name: showroom-api
    restart: always
    depends_on:
      - postgres
    networks:
      - showroom-network
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://showroom_user:🔑%20Ingresa%20contraseña%20de%20la%20base%20de%20datos%20(oculto,%20presiona%20Enter%20para%20usar%20el%20valor%20por%20defecto)@showroom-db:5432/showroom_db
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    container_name: showroom-db
    restart: always
    networks:
      - showroom-network
    environment:
      POSTGRES_USER: showroom_user
      POSTGRES_PASSWORD: "🔑 Ingresa contraseña de la base de datos (oculto, presiona Enter para usar el valor por defecto)"
      POSTGRES_DB: showroom_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  showroom-network:
    driver: bridge

volumes:
  pgdata:
